import {
  Image,
  Video,
  Edit,
  Sparkles,
  Palette,
  ZoomIn,
  Eraser,
  Expand,
  Brush,
  Layers,
  GraduationCap,
  Scissors,
} from "lucide-react"


export const features: Feature[] = [
  {
    name: "Image Generation",
    details: "Create stunning, high-resolution images from text prompts.",
    link: "/features/image-generation",
    isNew: true,
    icon: Image,
  },
  {
    name: "Video Generation",
    details: "Turn prompts into short AI-driven cinematic videos.",
    link: "/features/video-generation",
    isNew: true,
    icon: Video,
  },
  {
    name: "Photo Editing",
    details: "Edit, crop, and adjust photos with AI-powered tools.",
    link: "/features/photo-editing",
    isNew: false,
    icon: Edit,
  },
  {
    name: "AI Retouch",
    details: "Automatically enhance portraits with skin smoothing and tone correction.",
    link: "/features/retouch",
    isNew: false,
    icon: Sparkles,
  },
  {
    name: "Style Transfer",
    details: "Apply unique artistic styles to your images in seconds.",
    link: "/features/style-transfer",
    isNew: false,
    icon: Palette,
  },
  {
    name: "Super Resolution",
    details: "Upscale images by 2x–4x while preserving detail.",
    link: "/features/super-resolution",
    isNew: true,
    icon: ZoomIn,
  },
  {
    name: "Inpainting",
    details: "Remove or replace unwanted objects seamlessly.",
    link: "/features/inpainting",
    isNew: false,
    icon: Eraser,
  },
  {
    name: "Outpainting",
    details: "Expand images beyond their borders with AI context awareness.",
    link: "/features/outpainting",
    isNew: false,
    icon: Expand,
  },
  {
    name: "Realtime Canvas",
    details: "Draw, paint, and see instant AI-powered results as you create.",
    link: "/features/realtime-canvas",
    isNew: true,
    icon: Brush,
  },
  {
    name: "Batch Processing",
    details: "Process multiple images or videos at once for faster workflows.",
    link: "/features/batch",
    isNew: false,
    icon: Layers,
  },
  {
    name: "Custom Training",
    details: "Train models on your own datasets for personalized results.",
    link: "/features/training",
    isNew: true,
    icon: GraduationCap,
  },
  {
    name: "Background Removal",
    details: "Automatically remove or replace image backgrounds.",
    link: "/features/bg-removal",
    isNew: false,
    icon: Scissors,
  },
]
